### ISSUE TITLE
Implement SC-style event patterns.

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [josiah-wolf-oberholtzer/supriya#10]

**Comment by andrewyoung1991** [comment]
some implementation has been done [here](https://github.com/ideoforms/isobar/tree/master/isobar/pattern)

the design pattern itself is not ideal. using python generators is more ideal, for example an abstract base class may look like this:
```python
class Pattern(object):
    def __init__(self, length=None, **kwargs):
        self.length = length
        self._generator = None
        for key, value in kwargs.items():
            setattr(self, key, value)

    def __iter__(self):
        return self._get_generator()

    def __next__(self):
        if self._generator is None:
                self._get_generator()
        return next(self._generator)

    @property
    def is_infinite(self):
        return self.length is None

    def _get_generator(self):
        generator = self.make_generator()
        if self.is_infinite:
            self._generator = generator
        else:
            self._generator = (next(generator) for _ in range(self.length))
        return self._generator

    def make_generator(self):
        # user defined pattern generator
        raise NotImplementedError()


class PSeq(Pattern):
    def __init__(self, *args, **kwargs):
        assert "sequence" in kwargs
        super(PSeq, self).__init__(*args, **kwargs)

    def make_generator(self):
        import itertools
        return itertools.cycle(self.sequence)
```

**Comment by josiah-wolf-oberholtzer** [comment]
Cool. What you outline sounds similar to what I had been imagining for this. Generator-based patterns are ideal, especially if we can ultimately use Python's ``yield from`` construct to construct nested patterns. I'm not sure about caching the generator object on the pattern class - that can be problematic when implementing copy / deepcopy / pickle. But, not a big deal - I'm not sure how often one would copy a pattern anyways.

I'm also vaguely aware of Isobar, but I haven't played with it at all, so I can't comment on its design yet.

Implementing patterns in Supriya is low on my to-do list. Feel free to send me a pull request.

**Comment by andrewyoung1991** [comment]
:+1:  and let me know if I can jump on anything higher on the to-do list.

**Comment by josiah-wolf-oberholtzer** [comment]
I've been tied up with other things for months now, and looking over the issue tracker - it's all either drudgery (#5, #12) or speculative / experimental (#3, #6).

There are definitely a lot of concrete / solvable / non-pie-in-sky things to do not listed there. Patterns, tempo clocks, MIDI / polyphony voice dispatching, DAW-like affordances (mixers, mixer channels). I'll write some of them up and ping you.
