### ISSUE TITLE
Rename JSON keys in data for GUI implementation

### ISSUE THREAD

**Issue by delucis** [josiah-wolf-oberholtzer/supriya#106]
1. For ease of compatibility with Javascript, underscores should be preferred to hyphens.
  
    Known cases:
  
    - `server-tree` &rarr; `server_tree`
    - `server-meters` &rarr; `server_meters`

2. For consistency with the above I would also propose the following renaming:
    
    - `status` &rarr; `server_status`

**Comment by josiah-wolf-oberholtzer** [comment]
Done in https://github.com/josiah-wolf-oberholtzer/supriya/pull/105/commits/86b3f1021dbb289c4fad699b46e4e01306b38a53.

Will be merged shortly.
