### ISSUE TITLE
Open for collaboration?

### ISSUE THREAD

**Issue by deeuu** [josiah-wolf-oberholtzer/supriya#169]
Hi,

This is a very impressive project...great work!

I'd be interested in helping out with development if you have any areas that don't necessarily require a deep understanding of the codebase?

Cheers

**Comment by josiah-wolf-oberholtzer** [comment]
Hi!

Yes, I'm open to collaboration. Let me know if there's anything you're interested in or think is lacking.

Supriya is always lacking for usable docs or interesting examples.

The issue tracker here is probably not a good place to look - I've never used it faithfully.

Cheers

**Comment by deeuu** [comment]
Cool. I guess I can start trying to recreate examples from the SC docs, which will also help me to better understand the Supriya API.

**Comment by josiah-wolf-oberholtzer** [comment]
Yeah, that's a good approach. It will expose some of the gaps in what Supriya covers (although I'm not trying to do everything SC does, which is a ton).

One thing I had wanted was to have more interesting UGen examples, preferably based on the SC ones. Going that route would also expose which of the UGens I haven't ported to Supriya yet (e.g. what's in https://github.com/josiah-wolf-oberholtzer/supriya/tree/master/etc/pending_ugens).
