### ISSUE TITLE
Locate scsynth based on OS

### ISSUE THREAD

**Issue by deeuu** [josiah-wolf-oberholtzer/supriya#170]
Hey,

Should `scsynth.find` [search](https://github.com/josiah-wolf-oberholtzer/supriya/blob/master/supriya/scsynth.py#L160-L165) standard installation locations of SC? 

For example, on macOS, this would be `/Applications/SuperCollider.app/Contents/Resources/scsynth`.

No biggie, just thinking this was the first thing I had to look up to get the server going.

**Comment by josiah-wolf-oberholtzer** [comment]
Sounds like a good idea. Supriya had this feature years ago, but worth having again.
