### ISSUE TITLE
sc_plugins generic example?

### ISSUE THREAD

**Issue by styk-tv** [josiah-wolf-oberholtzer/supriya#176]
Since each plugin is a separate type and none are defined there seems to be no direct way to operate on any of the sc_plugins. If there is a chapter on this anywhere sorry for asking.

https://github.com/supercollider/sc3-plugins

Question: Is there a generic way to operate on plugins perhaps not as types but by means of build attributes?

**Comment by josiah-wolf-oberholtzer** [comment]
Apologies if I don't fully understand - I've never installed sc3-plugins. Are you asking how to use custom UGens with Supriya?

**Comment by styk-tv** [comment]
Yes I would love to learn how to do it and contribute if required. There are probably hundreds of others that are not in the sc3_plugins catalog. 
https://github.com/supercollider/sc3-plugins/tree/master/source



Or to start, how to handle this info in the builder so we don't have to create type for each one but rather have a generic way to describe them? Again, apologies if I missed this somewhere in the docs. Maybe its possible already?

https://doc.sccode.org/Guides/Tour_of_UGens.html

**Comment by styk-tv** [comment]
Digging around UGenBase and http://supriya.mbrsi.org/api/supriya/system/SupriyaObject.html#supriya.system.SupriyaObject.SupriyaObject but a specific, external implementation example would be a lifesaver.  (of how to make a new type)

**Comment by josiah-wolf-oberholtzer** [comment]
Historically I've used a combination of sclang and Python scripts to scrape the SC codebase for UGens, and then post-process the results into stubs for Python classes, which I then clean up manually. I'm not fond of a lot of the parameter names for many of the UGens, so I've been renaming many of them for clarity (scsynth doesn't care about the parameter names, just their order).

You can see some of the old dregs of that work here: https://github.com/josiah-wolf-oberholtzer/supriya/tree/master/etc. Those scripts probably don't work anymore, but you should be able to update them and dump out info about everything SC thinks is a UGen.

I've investigated concocting some more generic way to describe the UGens, e.g. from a JSON or YAML manifest, but nothing satisfies. Plus, if you've gone through the trouble to curate an accurate description of all the UGens in such a format, you're just a transformation away from generating the Python code for all of them and saving yourself from more confusing debugging.

As for examples, look at:
- https://github.com/josiah-wolf-oberholtzer/supriya/blob/master/supriya/ugens/AllpassN.py
- https://github.com/josiah-wolf-oberholtzer/supriya/blob/master/supriya/ugens/SinOsc.py
- https://github.com/josiah-wolf-oberholtzer/supriya/blob/master/supriya/ugens/PV_Add.py
- https://github.com/josiah-wolf-oberholtzer/supriya/blob/master/supriya/ugens/Gendy3.py
- https://github.com/josiah-wolf-oberholtzer/supriya/blob/master/supriya/ugens/Out.py (maybe the weirdest example)

The vast majority of the UGen classes look like the first four examples here.
- They inherit from UGen, or maybe from PureUGen or WidthFirstUGen
- They define `_valid_calculation_rates` as a tuple of `CalculationRate`s.
- They define `_ordered_input_names` as an ordered dict of parameter names and default values.

That's really it for 95% of the UGens we deal with.

**Comment by josiah-wolf-oberholtzer** [comment]
And some additional color: the reason we're able to define UGens with just `_valid_calculation_rates` and `_ordered_input_names` is because their [`UGenMeta` metaclass](https://github.com/josiah-wolf-oberholtzer/supriya/blob/master/supriya/synthdefs/bases.py#L15) builds out their constructors and properties based on those class variables automatically. Which means many UGen definitions fit on about 3-5 lines, depending on how many parameters they have.

**Comment by styk-tv** [comment]
wow, @josiah-wolf-oberholtzer, thank you. i'll spend some time with that now.

**Comment by josiah-wolf-oberholtzer** [comment]
Closing. Feel free to re-open if you have more questions.
