### ISSUE TITLE
supryia is no more compatible with python 3.7

### ISSUE THREAD

**Issue by MikHulk** [josiah-wolf-oberholtzer/supriya#207]
**Describe the bug**
The README claims that supriya is compatible with python 3.6. However it uses  [Assignment Expressions](https://www.python.org/dev/peps/pep-0572/) which are featured only in python 3.8.

**To Reproduce**
```
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import supriya
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mik/dev_python/supriya/supriya/__init__.py", line 49, in <module>
    from supriya.clocks import AsyncClock, AsyncOfflineClock, Clock, OfflineClock  # noqa
  File "/home/mik/dev_python/supriya/supriya/clocks/__init__.py", line 1, in <module>
    from .asynchronous import AsyncClock
  File "/home/mik/dev_python/supriya/supriya/clocks/asynchronous.py", line 7, in <module>
    from .bases import BaseClock
  File "/home/mik/dev_python/supriya/supriya/clocks/bases.py", line 574
    if (event_or_command := self.cancel(event_id)) is None:
                         ^
SyntaxError: invalid syntax
>>> 
```

**Environment (please complete the following information):**
 - OS: Linux 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) GNU/Linux
 - Python Version 3.7.3
 - SuperCollider Version 3.11.1.r395.gcd3b936457-1
 - Supriya Version 9f2c82fd3b42f7a3fbffe24bde3e9eed9e8ebb43

**Comment by josiah-wolf-oberholtzer** [comment]
True, rewriting the README is on my TODO list. See #198.

Feel free to send a PR bumping the claimed Python version requirement.

**Comment by MikHulk** [comment]
Ok thx Josiah. I will try to do the PR.  I tried to find how to downgrade my source code to a compatible version but I didn't find where to checkout (no tag, no branch, and the history doesn't show old commits). I am going to switch from my laptop to another device which have asdf installed. I could try with python 3.8. But I would like to try this on this laptop too.

**Comment by josiah-wolf-oberholtzer** [comment]
Bumped the claimed version support in the README to 3.8+.

**Comment by MikHulk** [comment]
I have found when the new syntax was introduced. 
https://github.com/josiah-wolf-oberholtzer/supriya/commit/7d3c4f87ea902a5fc1bc1beff029914882db8710

I didn't try yet but this version doesn't have assignment expression:
https://github.com/josiah-wolf-oberholtzer/supriya/tree/306672bf028871cd17c61fc28f6cbcd948801ffe

**Comment by MikHulk** [comment]
This change allow to import supriya in python 3.7:
```
diff --git a/supriya/clocks/bases.py b/supriya/clocks/bases.py
index 264bc579..32e8917c 100644
--- a/supriya/clocks/bases.py
+++ b/supriya/clocks/bases.py
@@ -571,7 +571,8 @@ class BaseClock:
     def reschedule(
         self, event_id, *, schedule_at=0.0, time_unit=TimeUnit.BEATS
     ) -> Optional[int]:
-        if (event_or_command := self.cancel(event_id)) is None:
+        event_or_command = self.cancel(event_id)
+        if event_or_command is None:
             return None
         if isinstance(event_or_command, (CallbackCommand, ChangeCommand)):
             command = event_or_command._replace(
diff --git a/supriya/scsynth.py b/supriya/scsynth.py
index e1ecef4c..2a36b47e 100644
--- a/supriya/scsynth.py
+++ b/supriya/scsynth.py
@@ -197,7 +197,8 @@ def find(scsynth_path=None):
     scsynth_path_candidates = uqbar.io.find_executable(scsynth_path.name)
     if scsynth_path_candidates:
         return pathlib.Path(scsynth_path_candidates[0])
-    if (fallback_path := _fallback_scsynth_path()) is not None:
+    fallback_path = _fallback_scsynth_path()
+    if fallback_path is not None:
         return fallback_path
     raise RuntimeError("Failed to locate scsynth")
 
```

I will try more deeply with this changes. I can make a PR for a version compatible with 3.7. You could maintain it in a separate branch waiting the 3.8 a full adoption . (Some distro doesn't upgrade to 3.8 yet)

**Comment by josiah-wolf-oberholtzer** [comment]
I'm not interested in reversing this change, and will probably incorporate more assignment expressions in the future. I'm definitely not interested in maintaining multiple branches for multiple Python versions.

**Comment by MikHulk** [comment]
I agree assignment expressions are convenient ;-)

Thx for your time
