### ISSUE TITLE
Convert test suit to use unittest.TestCase.

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [josiah-wolf-oberholtzer/supriya#27]
Convert all unit test modules to use `unittest.TestCase` or a subclass thereof. Abjad's `systemtools` provides a `TestCase` class with many convenience methods built-in. Supriya's tests should use either that class, or a custom subclass.

**Comment by kureta** [comment]
So I shouldn't use tox for now, right? Currently it fails for env py27 due to a line in patterntools: `yield from self._pattern`. Python 2.7 does not have `yield from`. Also some tests depend on system Sample Rate being set to 44100 Hz. Mine was 48 kHz and those tests have failed. I think test should be independent from system SR.

**Comment by josiah-wolf-oberholtzer** [comment]
Thanks for reminding me about `tox`. It hasn't been updated to reflect that 2.7 is no longer supported. I'll open an issue to update it.

Many tests actually boot SuperCollider and play audio through it. Some of these tests query the server for its state, including its internal sample rate, to prove that communication is working as expected. That doesn't seem to be a problem on OSX. SC just sets your system sample rate to match `scsynth`'s sample rate. Is that not the case on your system?

**Comment by kureta** [comment]
I am also on OSX and that was not the case. Most of the tests worked (after I removed all envs and added py35 instead) and some of them played sounds like you said. I guess it wasn't able to change my sample rate. I can update tox if you want.

**Comment by josiah-wolf-oberholtzer** [comment]
I'll try cleaning-up the `tox.ini` file. I have to fix-up the dependencies between `tox.ini`, `setup.py` and `requirements.txt` anyways.

**Comment by josiah-wolf-oberholtzer** [comment]
See #80 for `tox` clean-up.

**Comment by josiah-wolf-oberholtzer** [comment]
What version of SuperCollider do you have installed? I'm on 3.8dev. I
believe they've made some changes to support setting your sound-card's
sample-rate automatically.

**Comment by josiah-wolf-oberholtzer** [comment]
I've removed both tox and all uses of unittest. Regular pytest functions (with fixtures for setup/teardown) is now the preferred technique.
