### ISSUE TITLE
Code not waiting on asynchronous actions

### ISSUE THREAD

**Issue by alanbacon** [josiah-wolf-oberholtzer/supriya#326]
**Describe the bug**

I want to use supriya/super collider in an more programatic and less "live-coding" type of way. So using the example on the readme I combined all the commands into a single python script so I don't have to run the commands individually in a terminal. I put a wait on user input command towards the end of the script so the server won't shut down before I hear any sound.

However the synths don't play. I suspect this is because the code is attempting to add them to a group before the group has been created by the server, although this is just a guess.

I know that some operations in super collider have a callback, could this be used in anyway?
Or is there a way to inspect what groups are *actually* on the server so we can poll for the server state?

---

**To Reproduce**

Run this as a single script:
```python
import supriya
from supriya.ugens import EnvGen, Out, SinOsc
from supriya.synthdefs import Envelope, synthdef

server = supriya.Server().boot()

@synthdef()
def simple_sine(frequency=440, amplitude=0.1, gate=1):
    sine = SinOsc.ar(frequency=frequency) * amplitude
    envelope = EnvGen.kr(envelope=Envelope.adsr(), gate=gate, done_action=2)
    Out.ar(bus=0, source=[sine * envelope] * 2)


_ = server.add_synthdefs(simple_sine)


group = server.add_group() # code doesn't seem to wait here

for i in range(3):
    _ = group.add_synth(simple_sine, frequency=111 * (i + 1)) # so these synths don't play


input("Press Enter to stop the synths...")

for synth in group.children[:]:
     synth.free()
```

---

**Expected behavior**

I expect the same outcome from the script as when you enter each line from the script into a python terminal one-by-one.

**Environment (please complete the following information):**
 - OS: Windows
 - Python Version: 3.10.0
 - SuperCollider Version: 3.13.0
 - Supriya Version: last pip release (23.3b0)

---

**Additional context**

Perhaps I am approaching my use-case incorrectly? Is this what realtime and non-realtime contexts are supposed to be used for? It seems like the [documentation](https://github.com/josiah-wolf-oberholtzer/supriya/blob/main/docs/source/contexts.rst) has not yet been fully filled out for explaining these.

**Comment by josiah-wolf-oberholtzer** [comment]
Hi! The synths don't play because the server hasn't finished loading your SynthDef by the time you attempt to allocate the synths. 

You have a few options to guarantee the synths are allocated only after the SynthDef is ready:

1. Sync the server before allocating the synths:

```
_ = server.add_synthdefs(simple_sine)
server.sync()  # wait here for the async /d_recv to complete
group = server.add_group()
for i in range(3):
    _ = group.add_synth(simple_sine, frequency=111 * (i + 1))
```

2. (Usually better...) Use a "completion" context and allocate your synths (and group) in the "completion message" of the /d_recv. This is Supriya's take on the callback version you mention:

```
with server.at():  # start an OSC bundle to be executed ASAP
    with server.add_synthdefs(simple_sine):  # add SynthDefs and start collecting callback messages
        # the commands inside this block will be gathered into the completion OSC message
        # and will only be executed once the SynthDef is ready
        group = server.add_group()
        for i in range(3):
            _ = group.add_synth(simple_sine, frequency=111 * (i + 1))
```

2b. If you don't want to use the ``with ...`` blocks you can call ``server.add_synthdefs(simple_sine, on_completion=...)`` where the argument to ``on_completion`` is a function that takes the server as its only argument. Good for live-coding and using lambdas, but for more complex use cases you may just want to use the ``with`` context managers.

```
def callback(server):
    group = server.add_group()
    for i in range(3):
        _ = group.add_synth(simple_sine, frequency=111 * (i + 1))

server.add_synthdefs(simple_sine, on_completion=callback)
```

The ``with`` version and ``on_competion`` versions should result in identical OSC messages to the server.

---

You can inspect the server tree with:

```
print(server.query_tree())
```

Additionally, you can turn on OSC-level logging (very verbose!) by adding the following block to your script before you boot the server:

```
import logging
logging.basicConfig()
logging.getLogger("supriya.osc").setLevel(logging.DEBUG)
```

... which spits out a lot of stuff, but crucially shows the ``/fail`` messages explaining that your SynthDef wasn't found, just before the server reports that the SynthDef has finished loading:

```
DEBUG:supriya.osc.out:127.0.0.1:57110 OscMessage('/g_new', 1000, 0, 1)
INFO:supriya.osc:[127.0.0.1:57110] healthcheck: passed
DEBUG:supriya.osc.out:127.0.0.1:57110 OscMessage('/s_new', 'simple_sine', 1001, 0, 1000, 'frequency', 111.0)
DEBUG:supriya.osc.out:127.0.0.1:57110 OscMessage('/s_new', 'simple_sine', 1002, 0, 1000, 'frequency', 222.0)
DEBUG:supriya.osc.out:127.0.0.1:57110 OscMessage('/s_new', 'simple_sine', 1003, 0, 1000, 'frequency', 333.0)
Press Enter to stop the synths...DEBUG:supriya.osc.in:127.0.0.1:57110 OscMessage('/n_go', 1000, 1, -1, -1, 1, -1, -1)
DEBUG:supriya.osc.in:127.0.0.1:57110 OscMessage('/fail', '/s_new', 'SynthDef not found')
DEBUG:supriya.osc.in:127.0.0.1:57110 OscMessage('/fail', '/s_new', 'SynthDef not found')
DEBUG:supriya.osc.in:127.0.0.1:57110 OscMessage('/fail', '/s_new', 'SynthDef not found')
DEBUG:supriya.osc.in:127.0.0.1:57110 OscMessage('/done', '/d_recv')
```

With solution 2 (completions) the OSC messages look like this (where the big byte string is your compiled SynthDef):

```
DEBUG:supriya.osc.out:127.0.0.1:57110 OscMessage('/d_recv', b'SCgf\x00\x00\x00\x02\x00\x01\x0bsimple_sine\x00\x00\x00\n\x00\x00\x00\x00?\x80\x00\x00@\x00\x00\x00@@\x00\x00\xc2\xc6\x00\x00<#\xd7\n@\xa0\x00\x00\xc0\x80\x00\x00?\x00\x00\x00>\x99\x99\x9a\x00\x00\x00\x03=\xcc\xcc\xcdC\xdc\x00\x00?\x80\x00\x00\x00\x00\x00\x03\tamplitude\x00\x00\x00\x00\tfrequency\x00\x00\x00\x01\x04gate\x00\x00\x00\x02\x00\x00\x00\x06\x07Control\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x01\x01\x01\x06SinOsc\x02\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\xff\xff\xff\xff\x00\x00\x00\x00\x02\x0cBinaryOpUGen\x02\x00\x00\x00\x02\x00\x00\x00\x01\x00\x02\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x06EnvGen\x01\x00\x00\x00\x15\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\xff\xff\xff\xff\x00\x00\x00\x01\xff\xff\xff\xff\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x01\xff\xff\xff\xff\x00\x00\x00\x02\xff\xff\xff\xff\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x03\xff\xff\xff\xff\x00\x00\x00\x02\xff\xff\xff\xff\x00\x00\x00\x04\xff\xff\xff\xff\x00\x00\x00\x01\xff\xff\xff\xff\x00\x00\x00\x05\xff\xff\xff\xff\x00\x00\x00\x06\xff\xff\xff\xff\x00\x00\x00\x07\xff\xff\xff\xff\x00\x00\x00\x08\xff\xff\xff\xff\x00\x00\x00\t\xff\xff\xff\xff\x00\x00\x00\x06\xff\xff\xff\xff\x00\x00\x00\x07\xff\xff\xff\xff\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x01\xff\xff\xff\xff\x00\x00\x00\x06\xff\xff\xff\xff\x00\x00\x00\x07\x01\x0cBinaryOpUGen\x02\x00\x00\x00\x02\x00\x00\x00\x01\x00\x02\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x02\x03Out\x02\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00', OscBundle(
    contents=(
        OscMessage('/g_new', 1000, 0, 1),
        OscMessage('/s_new', 'simple_sine', 1001, 0, 1000, 'frequency', 111.0),
        OscMessage('/s_new', 'simple_sine', 1002, 0, 1000, 'frequency', 222.0),
        OscMessage('/s_new', 'simple_sine', 1003, 0, 1000, 'frequency', 333.0),
    ),
))
Press Enter to stop the synths...DEBUG:supriya.osc.in:127.0.0.1:57110 OscMessage('/n_go', 1000, 1, -1, -1, 1, -1, -1)
DEBUG:supriya.osc.in:127.0.0.1:57110 OscMessage('/n_go', 1001, 1000, -1, -1, 0)
DEBUG:supriya.osc.in:127.0.0.1:57110 OscMessage('/n_go', 1002, 1000, -1, 1001, 0)
DEBUG:supriya.osc.in:127.0.0.1:57110 OscMessage('/n_go', 1003, 1000, -1, 1002, 0)
DEBUG:supriya.osc.in:127.0.0.1:57110 OscMessage('/done', '/d_recv')
```

**Comment by alanbacon** [comment]
Hi!

Thanks for the quick and detailed response, and yes that worked.

Can't wait to get synthesising in a language that is easier than sclang!
