### ISSUE TITLE
Can't set multichannel synth controls

### ISSUE THREAD

**Issue by JordanHendersonMusic** [josiah-wolf-oberholtzer/supriya#339]
**Describe the bug**
I can't seem to set multichannel controls for synths. Not too sure if I have the syntax wrong, or if this is a bug?

**To Reproduce**
```python
@synthdef()
def sine_def(frequency=(440,412)):
    sine = SinOsc.ar(frequency=frequency)
    Out.ar(bus=0, source=sine)

print(sine_def)

server.add_synthdefs(sine_def)
sine = server.add_synth(sine_def)

sine.set(frequency=220) # sets left channel
sine.set(frequency=(220, 310)) # type error
sine.set(frequency=[220, 310]) # type error
```

**Expected behavior**
Both channels to be set through the Tuple

**Environment (please complete the following information):**
 - OS: Linux Manjaro
 - Python Version 3.10
 - SuperCollider Version 3.12 (or something newer as I compile it from source pretty regularly)
 - Supriya Version 23.5b6

**Comment by josiah-wolf-oberholtzer** [comment]
OK, sounds legit. I just noticed the fine-print in the [server command reference](https://doc.sccode.org/Reference/Server-Command-Reference.html) about `/n_set` supporting arrays as values. I'll take a look at implementing soon.

**Comment by josiah-wolf-oberholtzer** [comment]
@JordanHendersonMusic try out https://github.com/josiah-wolf-oberholtzer/supriya/pull/340 and let me know if the updated `.set_node()` method does what you need.

**Comment by JordanHendersonMusic** [comment]
amazing! I'll get right on it.


I also started a discussion #338 - could have been an issue/request.

**Comment by JordanHendersonMusic** [comment]
Works perfectly, thanks for the fast response

**Comment by josiah-wolf-oberholtzer** [comment]
> amazing! I'll get right on it.
> 
> I also started a discussion #338 - could have been an issue/request.

Saw the discussion. I'll leave a response after I've mulled it over.
