### ISSUE TITLE
Restructure all docstrings

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [josiah-wolf-oberholtzer/supriya#34]
Restructure docstrings from:

    class Foo(object):
        '''Blah blah.
        '''

... to ...

    class Foo(object):
        '''
        Blah blah.
        '''

It looks nicer.

**Comment by kureta** [comment]
But this way docstrings will be starting with an empty line. Do all docstring parser/processor tools trim newlines appropriately?

**Comment by josiah-wolf-oberholtzer** [comment]
It works fine with the `ajv doctest` script.

I'm currently verifying that it works correctly for building documentation via Sphinx. If there's a problem them, I'll just fix it in our doc-building toolchain. Will probably require pulling a new version of Abjad.

**Comment by josiah-wolf-oberholtzer** [comment]
Neither the docs nor the doctests are a blocker for this issue. All docstrings can be rewritten like:

```
class Foo(object):
    """
    Blah blah.
    """
```

**Comment by kureta** [comment]
I wrote and successfully tested a regex to do this, and to add a newline to the ends of files where there is none. Should I add missing newlines only in .py files or all files, because some .rst files also don't have a newline at the end?

**Comment by josiah-wolf-oberholtzer** [comment]
You can add newlines in .rst files. Could you do the newlines in a separate PR (with .py separate from .rst)? Separate PRs will be easier for me to review, and will help us manage merge conflicts more easily.

**Comment by kureta** [comment]
There are no .rst files missing a newline at the end, and I just sent a PR for .py files. So you can close this issue.

**Comment by josiah-wolf-oberholtzer** [comment]
@kureta Nice! Thanks so much for diving into this stuff! This project is far, far from done. I really appreciate all the help I can get.

**Comment by kureta** [comment]
Thank you for starting such an awesome project. I will continue to do whatever I can. As I get more familiar with the code I hope to be more useful.

**Comment by josiah-wolf-oberholtzer** [comment]
If you want to keep helping, and want suggestions for what to look at, just ask. I'm trying to update many of the issues with better descriptions so people can determine how complex they are.
