### ISSUE TITLE
Does the quickstart demo produce sound?

### ISSUE THREAD

**Issue by shakfu** [josiah-wolf-oberholtzer/supriya#341]
Hi, I was able to get supriya running on a raspberrypi without issues and I ran the quickstart and received the textual output as expected but no sound.

Was it supposed to trigger some audio or something?

**Comment by josiah-wolf-oberholtzer** [comment]
Yes it should, and it does for me.

Take a look at this previous issue for troubleshooting techniques: https://github.com/josiah-wolf-oberholtzer/supriya/issues/326
