### ISSUE TITLE
README has invalid instructions

### ISSUE THREAD

**Issue by keckler** [josiah-wolf-oberholtzer/supriya#343]
I don't really know anything about this software, but I tried to follow the startup instructions in the README and found that there are some calls that aren't valid. Specifically:

https://github.com/josiah-wolf-oberholtzer/supriya/blob/2ebf835ce9bbfca19e4220628a32c30fa66e04f7/README.md?plain=1#L90-L92

The `Server`/`BaseServer` object doesn't appear to have an `add_synthdefs()` method.

**Comment by josiah-wolf-oberholtzer** [comment]
Are you talking about this `add_synthdefs()` method? https://github.com/josiah-wolf-oberholtzer/supriya/blob/main/supriya/contexts/core.py#L629

**Comment by keckler** [comment]
```
In [3]: import supriya

In [4]: supriya.__version__
Out[4]: '23.2b1'

In [5]: server = supriya.Server().boot()

In [6]: _ = server.add_synthdefs(supriya.default)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-a7c5f7e1f7ed> in <module>
----> 1 _ = server.add_synthdefs(supriya.default)

AttributeError: 'Server' object has no attribute 'add_synthdefs'
```

**Comment by josiah-wolf-oberholtzer** [comment]
You're quite a few versions behind the latest, so it's no wonder the current instructions don't work. Try upgrading.

**Comment by josiah-wolf-oberholtzer** [comment]
You'll also want to use a newer version of Python. Recent versions of Supriya don't run on Python 3.7 anymore.

**Comment by keckler** [comment]
Huh, okay, this was just the version that pip grabbed for me. I didn't expect that it would be out of date. 

But yep, you're right, upgrade fixed it. Sorry for the bother!

**Comment by josiah-wolf-oberholtzer** [comment]
The version you got was probably the last version that supported Python 3.7 😄
