### ISSUE TITLE
Binary OP ugen shortcuts

### ISSUE THREAD

**Issue by scottyeager** [josiah-wolf-oberholtzer/supriya#351]
Looks like there's a missing negative sign on line 4120:

https://github.com/josiah-wolf-oberholtzer/supriya/blob/6a12db6663617a782e00363ed03083bbe5b0850c/supriya/ugens/bases.py#L4118-L4125

**Comment by josiah-wolf-oberholtzer** [comment]
Nice catch. Working on fixing this today.
