### ISSUE TITLE
Add overloads for bitwise binary OP ugens

### ISSUE THREAD

**Issue by scottyeager** [josiah-wolf-oberholtzer/supriya#352]
In sclang, creating binary OP ugens using the bitwise operators (`&` and `|`, at least) is supported. Would be nice to also have this in Supriya, by adding `__or__` and `__and__` to the overloaded operators.

For example:

```
@synthdef()
def gated(gate=1, time=1):
    Linen.kr(gate & Trig.kr(1, time))
```

**Comment by josiah-wolf-oberholtzer** [comment]
Sounds good to me. Will have this implemented today.

**Comment by scottyeager** [comment]
Excellent, thanks!
