### ISSUE TITLE
Code in README.rst does not work

### ISSUE THREAD

**Issue by kureta** [josiah-wolf-oberholtzer/supriya#36]
When I try to run the code example in your readme file it throws this error:

```
Traceback (most recent call last):
  File "/Users/kureta/Documents/Python/supriya-sandbox/main.py", line 24, in <module>
    source = source * builder['amplitude']
  File "/Users/kureta/Documents/Python/supriya/supriya/tools/synthdeftools/UGenMethodMixin.py", line 898, in __mul__
    synthdeftools.BinaryOperator.MULTIPLICATION,
  File "/Users/kureta/Documents/Python/supriya/supriya/tools/synthdeftools/UGenMethodMixin.py", line 1676, in _compute_binary_op
    special_index=special_index,
  File "/Users/kureta/Documents/Python/supriya/supriya/tools/ugentools/BinaryOpUGen.py", line 67, in _new_single
    if b == 0:
  File "/Users/kureta/Documents/Python/supriya/supriya/tools/synthdeftools/Parameter.py", line 58, in __eq__
    return systemtools.TestManager.compare_objects(self, expr)
AttributeError: type object 'TestManager' has no attribute 'compare_objects'
```

**Comment by josiah-wolf-oberholtzer** [comment]
I'm sure it's broken - nothing tests those examples at the moment.

Install Abjad directly from the Abjad repository on Github (https://github.com/Abjad/abjad) and try again.

**Comment by kureta** [comment]
Thanks, it works.

**Comment by josiah-wolf-oberholtzer** [comment]
Cool, and thanks for the notice.

Supriya and Abjad are sister-projects. Supriya closely follows the development cycle of Abjad, and relies on the newest changes there.

Eventually the two projects will stabilize more and this sort of thing will be less of a problem.

**Comment by kureta** [comment]
Isn't Abjad all about generating score/notation? What do you used Abjad for in this project, if I may ask?

**Comment by josiah-wolf-oberholtzer** [comment]
Abjad _is_ for generating notation, but it has a large library of other tools - for building documentation, creating graphs, tools for string processing, math and sequence-manipulation etc, and tools for modeling events-in-time.

My long-term goal is for Supriya to interface closely with Abjad to make creating combination-acoustic-electronic pieces simple.

**Comment by josiah-wolf-oberholtzer** [comment]
@kureta Is this issue still valid for you?

**Comment by kureta** [comment]
It is not an issue anymore but if the README does not say "install Abjad from source" it means the issue about the README is not solved. Right? Also I guess "Consult our installation instructions for detailed help on getting Abjad" means "consult Abjad's installation instructions" because we don't have any installation instructions other than what is included in the README and the wording is a bit misleading.

**Comment by josiah-wolf-oberholtzer** [comment]
Hah, fair. I need to work on releasing Abjad v2.19 so I can require that specific version in Supriya's installer automatically.

I'll leave this issue open until I correct this mess.

**Comment by josiah-wolf-oberholtzer** [comment]
OK, Abjad 2.19 has been released. I pinned Supriya's Abjad dependency to v2.19. All tests pass. I'll update the README documentation soon to reflect this.

**Comment by josiah-wolf-oberholtzer** [comment]
Moot.
